### ISSUE TITLE
After updating Torch to a version that supports CUDA, I get an error with a subprocess call

### ISSUE THREAD

**Issue by HopperElec** [minimaxir/aitextgen#112]
By default, pip install aitextgen installs a version of Torch that does not support CUDA and thus not allowing me to use my GPU. But after updating the version of Torch (same version, just with +cu102) I get the following error```
Traceback (most recent call last):
  File "c:/Users/hoppe/aitextgen/main.py", line 46, in <module>
    data[1].train(data[0], dir+model+"/", batch_size=32, num_steps=steps, progress_bar_refresh_rate=32, save_every=steps, generate_every=steps)
  File "C:\Users\hoppe\AppData\Local\Programs\Python\Python38\lib\site-packages\aitextgen\aitextgen.py", line 712, in train
    trainer.fit(train_model)
  File "C:\Users\hoppe\AppData\Local\Programs\Python\Python38\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 499, in fit
    self.dispatch()
  File "C:\Users\hoppe\AppData\Local\Programs\Python\Python38\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 546, in dispatch
    self.accelerator.start_training(self)
  File "C:\Users\hoppe\AppData\Local\Programs\Python\Python38\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 73, in start_training
    self.training_type_plugin.start_training(trainer)
  File "C:\Users\hoppe\AppData\Local\Programs\Python\Python38\lib\site-packages\pytorch_lightning\plugins\training_type\training_type_plugin.py", line 114, in start_training
    self._results = trainer.run_train()
  File "C:\Users\hoppe\AppData\Local\Programs\Python\Python38\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 637, in run_train
    self.train_loop.run_training_epoch()
  File "C:\Users\hoppe\AppData\Local\Programs\Python\Python38\lib\site-packages\pytorch_lightning\trainer\training_loop.py", line 505, in run_training_epoch
    self.on_train_batch_end(epoch_output, batch_end_outputs, batch, batch_idx, dataloader_idx)
  File "C:\Users\hoppe\AppData\Local\Programs\Python\Python38\lib\site-packages\pytorch_lightning\trainer\training_loop.py", line 208, in on_train_batch_end
    self.trainer.call_hook('on_batch_end')
  File "C:\Users\hoppe\AppData\Local\Programs\Python\Python38\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1091, in call_hook
    trainer_hook(*args, **kwargs)
  File "C:\Users\hoppe\AppData\Local\Programs\Python\Python38\lib\site-packages\pytorch_lightning\trainer\callback_hook.py", line 145, in on_batch_end
    callback.on_batch_end(self, self.lightning_module)
  File "C:\Users\hoppe\AppData\Local\Programs\Python\Python38\lib\site-packages\aitextgen\train.py", line 160, in on_batch_end
    result = subprocess.run(
  File "C:\Users\hoppe\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\hoppe\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\hoppe\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1251, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\hoppe\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 553, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "C:\Users\hoppe\AppData\Local\Programs\Python\Python38\lib\os.py", line 818, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by minimaxir** [comment]
> By default, pip install aitextgen installs a version of Torch that does not support CUDA and thus not allowing me to use my GPU. 

I'm less familiar with how CUDA works on Windows but the installed version from pip will be whatever's stable. aitextgen just sets a minimum PyTorch.

From the stack trace it seems that it's something at the pytorch-lightning level and maybe not CUDA. Does the CPU demo work / have the same issue?

**Comment by HopperElec** [comment]
Before I updated, my script worked fine, so I suppose that means the CPU version works

**Comment by HopperElec** [comment]
Also, it's worth noting I'm using the GPT2ConfigCPU, both before and after to update

**Comment by Caesium2021** [comment]
Try to add nvidia-smi to your PATHS in system environements variables.I had this problem since nvidia-smi is not in your paths running it will return none to shutils.wich('nvidia-smi') where it should return the config of your gpu.

**Comment by HopperElec** [comment]
Could you clarify? As in, am I adding this to my user variables or my system variables, and exactly what is the path I need to add? I've found https://stackoverflow.com/questions/57100015/how-do-i-run-nvidia-smi-on-windows which says the executable is located at C:\Windows\System32\DriverStore\FileRepository\nvdm*\nvidia-smi.exe but found nothing about adding it to PATH so unsure if I'm adding just the folder, if I'm adding the exe or if you meant to literally add 'nvidia-smi'

**Comment by HopperElec** [comment]
I think I've not tried every combination of nvidia-smi in PATH. I seem to have it in 3 locations on my computer, so I've tried all of them in both the user variables and system variables and both with the .exe, without the .exe and just the folder. None of them seem to have fixed the issue, so unless I've missed something this doesn't seem to be the issue

**Comment by Caesium2021** [comment]
Be sure to double click on the path variable then press add and then you will indicate the directory where nvvidia-smi is located.It should not allow you to pick the exe.

**Comment by HopperElec** [comment]
Which PATH, there are two (user and system). There is no 'add' button- I'm adding by double clicking on an empty row and it makes a new one for me to type in- this is correct, right? Which directory (as I said, I have multiple- C:\Program Files\NVIDIA Corporation\NVSMI and C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_cc5a8fceed9bb371. I thought there was a third I tried but I think I'm just remembering me trying to find C:\Windows\System32\DriverStore\FileRepository\nvdm*\ but this doesn't seem to exist on my computer). It does allow me to pick the exe, but thanks for clarifying it is the directory I am adding.

**Comment by Caesium2021** [comment]
On the right side of the panel there should be a new button,the you click browse and pick C:\Program Files\NVIDIA Corporation\NVSM.You may have to restart your computer.You can put it in system if there are more users that will be using it or in users env for yourself.

**Comment by HopperElec** [comment]
Ah, it seems it's restarting my computer that solved it- usually I don't have to for updating PATH. Thanks, it works now!
