### ISSUE TITLE
enormous, horrifying error message spontaneously appears

### ISSUE THREAD

**Issue by cybergrunge-ops** [minimaxir/aitextgen#164]
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_qint8 = np.dtype([("qint8", np.int8, 1)]) /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_quint8 = np.dtype([("quint8", np.uint8, 1)]) /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_qint16 = np.dtype([("qint16", np.int16, 1)]) /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_quint16 = np.dtype([("quint16", np.uint16, 1)]) /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_qint32 = np.dtype([("qint32", np.int32, 1)]) /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. np_resource = np.dtype([("resource", np.ubyte, 1)]) /usr/local/lib/python3.7/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_qint8 = np.dtype([("qint8", np.int8, 1)]) /usr/local/lib/python3.7/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_quint8 = np.dtype([("quint8", np.uint8, 1)]) /usr/local/lib/python3.7/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_qint16 = np.dtype([("qint16", np.int16, 1)]) /usr/local/lib/python3.7/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_quint16 = np.dtype([("quint16", np.uint16, 1)]) /usr/local/lib/python3.7/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_qint32 = np.dtype([("qint32", np.int32, 1)]) /usr/local/lib/python3.7/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. np_resource = np.dtype([("resource", np.ubyte, 1)]) Traceback (most recent call last): File "/usr/local/bin/aitextgen", line 6, in from aitextgen.cli import aitextgen_cli File "/usr/local/lib/python3.7/dist-packages/aitextgen/__init__.py", line 1, in from .aitextgen import aitextgen # noqa File "/usr/local/lib/python3.7/dist-packages/aitextgen/aitextgen.py", line 11, in import pytorch_lightning as pl File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/__init__.py", line 20, in from pytorch_lightning import metrics # noqa: E402 File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/__init__.py", line 15, in from pytorch_lightning.metrics.classification import ( # noqa: F401 File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/classification/__init__.py", line 14, in from pytorch_lightning.metrics.classification.accuracy import Accuracy # noqa: F401 File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/classification/accuracy.py", line 16, in from torchmetrics import Accuracy as _Accuracy File "/usr/local/lib/python3.7/dist-packages/torchmetrics/__init__.py", line 14, in from torchmetrics import functional # noqa: E402 File "/usr/local/lib/python3.7/dist-packages/torchmetrics/functional/__init__.py", line 60, in from torchmetrics.functional.text.bert import bert_score File "/usr/local/lib/python3.7/dist-packages/torchmetrics/functional/text/bert.py", line 28, in from transformers import AutoModel, AutoTokenizer File "/usr/local/lib/python3.7/dist-packages/transformers/__init__.py", line 43, in from . import dependency_versions_check File "/usr/local/lib/python3.7/dist-packages/transformers/dependency_versions_check.py", line 36, in from .file_utils import is_tokenizers_available File "/usr/local/lib/python3.7/dist-packages/transformers/file_utils.py", line 81, in _tf_available = importlib.util.find_spec("tensorflow") is not None File "/usr/lib/python3.7/importlib/util.py", line 114, in find_spec raise ValueError('{}.__spec__ is None'.format(name)) ValueError: tensorflow.__spec__ is None

**Comment by cybergrunge-ops** [comment]
reinstalling dependencies as specified worked fine. must be a problem with pip or tf
