### ISSUE TITLE
Bolded Prompt text limits available character sequences

### ISSUE THREAD

**Issue by xeb** [minimaxir/aitextgen#17]
A user is unable to generate text with a pipe (`|`) or another character used in a regular expression. Doing so will result in the following exception:
Example:
```
ai.generate(1, prompt_text="This is | a test |")
INFO:aitextgen:Loading GPT-2 model from provided trained_model/pytorch_model.bin.
INFO:aitextgen:Using a custom tokenizer.
Traceback (most recent call last):
  File "./chatbot-infer.py", line 21, in <module>
    ai.generate(1, prompt="0|agent1|what are you doing?")
  File ".../lib/python3.7/site-packages/aitextgen/aitextgen.py", line 301, in generate
    for text in gen_texts
  File ".../lib/python3.7/site-packages/aitextgen/aitextgen.py", line 301, in <listcomp>
    for text in gen_texts
  File "/usr/lib/python3.7/re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib/python3.7/re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.7/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.7/sre_parse.py", line 924, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.7/sre_parse.py", line 420, in _parse_sub
    not nested and not items))
  File "/usr/lib/python3.7/sre_parse.py", line 645, in _parse
    source.tell() - here + len(this))
re.error: nothing to repeat at position 3

```

This appears to be due to: https://github.com/minimaxir/aitextgen/blob/master/aitextgen/aitextgen.py#L299 where the prompt_text is being used in a regex. 

Would it be better to do string substitution or just eliminate the bolding feature?

For context, I have a GPT2 model and custom dataset that uses pipes `|` in sequences to denote agents. I'd be happy to remove the bolding feature, especially given that it is a display/presentation feature not necessarily something the library should be doing (IMO).

**Comment by minimaxir** [comment]
See also #8 

String substitution might be better. But I am not removing the bolding option as it’s important for usability. (and it’s a visibility option that doesn’t affect the underlying data)

**Comment by minimaxir** [comment]
In the short term, you bypass both concerns by using `generate_one()`

**Comment by xeb** [comment]
Awesome, thanks!
