### ISSUE TITLE
ImportError: cannot import name '_TPU_AVAILABLE' from 'pytorch_lightning.utilities' 

### ISSUE THREAD

**Issue by ZT00OK53** [minimaxir/aitextgen#207]
2023-01-23 16:21:27.089807: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-01-23 16:21:27.090522: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "D:\AI\aitextgen\my.py", line 1, in <module>
    from aitextgen import aitextgen
  File "D:\AI\aitextgen\aitextgen\__init__.py", line 1, in <module>
    from .aitextgen import aitextgen  # noqa
  File "D:\AI\aitextgen\aitextgen\aitextgen.py", line 31, in <module>
    from .train import ATGProgressBar, ATGTransformer
  File "D:\AI\aitextgen\aitextgen\train.py", line 14, in <module>
    from pytorch_lightning.utilities import _TPU_AVAILABLE
ImportError: cannot import name '_TPU_AVAILABLE' from 'pytorch_lightning.utilities' (C:\Users\OmkarKurmi\AppData\Local\Programs\Python\Python39\lib\site-packages\pytorch_lightning\utilities\__init__.py)

ImportError: cannot import name '_TPU_AVAILABLE' from 'pytorch_lightning.utilities' 

While ruining on google colab and local machine I getting above.

Could you please guide me how I can fix it

**Comment by 2br-2b** [comment]
Duplicate of #200 - there's also a solution lister there
