### ISSUE TITLE
ImportError: cannot import name 'ProgressBarBase' from 'pytorch_lightning.callbacks.progress'

### ISSUE THREAD

**Issue by dumpsters** [minimaxir/aitextgen#214]
Trying to run this on WSL, did pip3 install aitextgen and using the training code from the repository.
Also commented out line 14 as per https://github.com/minimaxir/aitextgen/commit/78a0bfdfaff917cad6430d0d12b43f58a4b3226d
```
./train.py                                                                                
Traceback (most recent call last):
  File "/home/user/aitextgen/./train.py", line 3, in <module>
    from aitextgen.TokenDataset import TokenDataset
  File "/home/user/.local/lib/python3.10/site-packages/aitextgen/__init__.py", line 1, in <module>
    from .aitextgen import aitextgen  # noqa
  File "/home/user/.local/lib/python3.10/site-packages/aitextgen/aitextgen.py", line 31, in <module>
    from .train import ATGProgressBar, ATGTransformer
  File "/home/user/.local/lib/python3.10/site-packages/aitextgen/train.py", line 13, in <module>
    from pytorch_lightning.callbacks.progress import ProgressBarBase
ImportError: cannot import name 'ProgressBarBase' from 'pytorch_lightning.callbacks.progress' (/home/user/.local/lib/python3.10/site-packages/pytorch_lightning/callbacks/progress/__init__.py)
```

**Comment by scorixear** [comment]
#216 seems like to fix your issue. I had additional erros when running the example (`KeyError loss in metrics['loss']`).
Its just general problems with the requirements of this project not setting an upper bound for pytorch lightning.
Version 2.0.0 had some breaking changes in Lightning, hence this code is not working
