### ISSUE TITLE
still getting the same error. 

### ISSUE THREAD

**Issue by koutkout** [minimaxir/aitextgen#218]
I tried different lightning versions and it didn't work. I rolled back to 0.4.2 and although generation was running fine but training wasn't running!
I now have  aitextgen 0.6.0 with pytorch-lightning 1.7.0
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Traceback (most recent call last):
  File "trainai\[trainai.py](http://trainai.py/)", line 28, in <module>
    ai.train(data, batch_size=8, num_steps=50000, generate_every=5000)
  File "C:\Python310\lib\site-packages\aitextgen\[aitextgen.py](http://aitextgen.py/)", line 752, in train
    trainer.fit(train_model)
  File "C:\Python310\lib\site-packages\pytorch_lightning\trainer\[trainer.py](http://trainer.py/)", line 700, in fit
    self._call_and_handle_interrupt(
  File "C:\Python310\lib\site-packages\pytorch_lightning\trainer\[trainer.py](http://trainer.py/)", line 654, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "C:\Python310\lib\site-packages\pytorch_lightning\trainer\[trainer.py](http://trainer.py/)", line 741, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "C:\Python310\lib\site-packages\pytorch_lightning\trainer\[trainer.py](http://trainer.py/)", line 1147, in _run
    self.strategy.setup(self)
  File "C:\Python310\lib\site-packages\pytorch_lightning\strategies\[single_device.py](http://single_device.py/)", line 74, in setup
    super().setup(trainer)
  File "C:\Python310\lib\site-packages\pytorch_lightning\strategies\[strategy.py](http://strategy.py/)", line 153, in setup
    self.setup_optimizers(trainer)
  File "C:\Python310\lib\site-packages\pytorch_lightning\strategies\[strategy.py](http://strategy.py/)", line 141, in setup_optimizers
    self.optimizers, self.lr_scheduler_configs, self.optimizer_frequencies = _init_optimizers_and_lr_schedulers(
  File "C:\Python310\lib\site-packages\pytorch_lightning\core\[optimizer.py](http://optimizer.py/)", line 194, in _init_optimizers_and_lr_schedulers
    _validate_scheduler_api(lr_scheduler_configs, model)
  File "C:\Python310\lib\site-packages\pytorch_lightning\core\[optimizer.py](http://optimizer.py/)", line 351, in _validate_scheduler_api
    raise MisconfigurationException(
pytorch_lightning.utilities.exceptions.MisconfigurationException: The provided lr scheduler `LambdaLR` doesn't follow PyTorch's LRScheduler API. You should override the `LightningModule.lr_scheduler_step` hook with your own logic if you are using a custom LR scheduler.

=============
if i upgrade to lightning==2.0.0 then I will get:
Traceback (most recent call last):
  File "trainai\[trainai.py](http://trainai.py/)", line 1, in <module>
    from aitextgen.TokenDataset import TokenDataset
  File "C:\Python310\lib\site-packages\aitextgen\[__init__.py](http://__init__.py/)", line 1, in <module>
    from .aitextgen import aitextgen  # noqa
  File "C:\Python310\lib\site-packages\aitextgen\[aitextgen.py](http://aitextgen.py/)", line 14, in <module>
    from pytorch_lightning.plugins import DeepSpeedPlugin
ImportError: cannot import name 'DeepSpeedPlugin' from 'pytorch_lightning.plugins' (C:\Python310\lib\site-packages\pytorch_lightning\plugins\__init__.py)

Please help.

**Comment by astrolul** [comment]
Same I recently tried this out and I was getting all sorts of errors, let me know when this is fixed because I want to use it ASAP.

**Comment by koutkout** [comment]
Thanks. It was solved earlier. But now there's another problem. I remember testing it a week ago and it was working but for unknown reason it's not working now.
ImportError                               Traceback (most recent call last)
<ipython-input-12-788200466e82> in <cell line: 1>()
----> 1 from aitextgen import aitextgen
      2 from aitextgen.colab import mount_gdrive, copy_file_from_gdrive
      3 ai = aitextgen(tf_gpt2="124M", to_gpu=True)

1 frames
/usr/local/lib/python3.9/dist-packages/aitextgen/aitextgen.py in <module>
     12 import torch
     13 from pkg_resources import resource_filename
---> 14 from pytorch_lightning.plugins import DeepSpeedPlugin
     15 from tqdm.auto import trange
     16 from transformers import (

ImportError: cannot import name 'DeepSpeedPlugin' from 'pytorch_lightning.plugins' (/usr/local/lib/python3.9/dist-packages/pytorch_lightning/plugins/__init__.py)
