### ISSUE TITLE
Unable to finetune distilgpt and save beyond 1000 steps

### ISSUE THREAD

**Issue by pdsing** [minimaxir/aitextgen#62]
I am using a GTX 1080Ti machine with 11 GB GPU RAM. I am able to finetune and save the default GPT (124M) model with 5000 steps. I am not able to finetune and save the distilGPT model beyond 1000 steps. When I finetune for 900 steps, I am able to finetune and save the model.

I am copying below the command prompt and the error that I get while saving at the 1000 step -

(gpt) pdsingh@pdsingh-MS-7C31:~/projects/pd/aitextgen$ python finetune_distilgpt.py 
[00:00:00] Reading files                            ████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                 100
[00:00:00] Tokenize words                           ████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 10378    /    10378
[00:00:00] Count pairs                              ████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 10378    /    10378
[00:00:00] Compute merges                           ████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 4743     /     4743

INFO:aitextgen.tokenizers:Saving aitextgen-vocab.json and aitextgen-merges.txt to the current directory. You will need both files to build the GPT2Tokenizer.
INFO:aitextgen:Loading distilgpt2 model from /aitextgen.
INFO:aitextgen:Using a custom tokenizer.
  0%|                                                                                                                                                             | 0/22940 [00:00<?, ?it/s]INFO:aitextgen.TokenDataset:Encoding 22,940 sets of tokens from input2.txt.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22940/22940 [00:00<00:00, 112065.27it/s]
GPU available: True, used: True
INFO:lightning:GPU available: True, used: True
No environment variable for node rank defined. Set as 0.
WARNING:lightning:No environment variable for node rank defined. Set as 0.
CUDA_VISIBLE_DEVICES: [0]
INFO:lightning:CUDA_VISIBLE_DEVICES: [0]
1,000 steps reached: saving model to /trained_model                                                                                                                                         
1,000 steps reached: generating sample texts.                                                                                                                                               
Loss: 3.899 — Avg: 3.916 — GPU Mem: 4276 MB:  50%|███████████████████████████████████████████████████                                                   | 1000/2000 [02:02<02:02,  8.18it/s]Traceback (most recent call last):
  File "finetune_distilgpt.py", line 30, in <module>
    ai.train(data, batch_size=16, num_steps=2000)
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/aitextgen/aitextgen.py", line 565, in train
    trainer.fit(train_model)
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 859, in fit
    self.single_gpu_train(model)
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 503, in single_gpu_train
    self.run_pretrain_routine(model)
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1015, in run_pretrain_routine
    self.train()
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 347, in train
    self.run_training_epoch()
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 419, in run_training_epoch
    _outputs = self.run_training_batch(batch, batch_idx)
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 638, in run_training_batch
    self.on_batch_end()
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/pytorch_lightning/trainer/callback_hook.py", line 63, in on_batch_end
    callback.on_batch_end(self, self.get_model())
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/aitextgen/train.py", line 187, in on_batch_end
    self.generate_sample_text(trainer, pl_module)
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/aitextgen/train.py", line 204, in generate_sample_text
    for output in outputs
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/aitextgen/train.py", line 204, in <listcomp>
    for output in outputs
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 2181, in decode
    sub_texts.append(self.convert_tokens_to_string(current_sub_text))
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/transformers/tokenization_gpt2.py", line 235, in convert_tokens_to_string
    text = "".join(tokens)
TypeError: sequence item 0: expected str instance, NoneType found
Exception ignored in: <function tqdm.__del__ at 0x7fbae51b8b90>
Traceback (most recent call last):
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/tqdm/std.py", line 1131, in __del__
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/tqdm/std.py", line 1344, in close
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/tqdm/std.py", line 1523, in display
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/tqdm/std.py", line 1134, in __repr__
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/tqdm/std.py", line 1484, in format_dict
TypeError: cannot unpack non-iterable NoneType object

I am using the following code -
`
from aitextgen.TokenDataset import TokenDataset
from aitextgen.tokenizers import train_tokenizer
from aitextgen.utils import GPT2ConfigCPU
from aitextgen import aitextgen

if __name__ == '__main__':
    # The name of the pros text for training
    file_name = "input2.txt"

    # Train a custom BPE Tokenizer on the downloaded text
    # This will save two files: aitextgen-vocab.json and aitextgen-merges.txt,
    # which are needed to rebuild the tokenizer.
    train_tokenizer(file_name)
    vocab_file = "aitextgen-vocab.json"
    merges_file = "aitextgen-merges.txt"

    # Instantiate aitextgen using the created tokenizer and config
    # ai = aitextgen(vocab_file=vocab_file, merges_file=merges_file, config=config)
    # Todo: Check if we need the config.json for this one
    ai = aitextgen(vocab_file=vocab_file, merges_file=merges_file, model="distilgpt2")

    # You can build datasets for training by creating TokenDatasets,
    # which automatically processes the dataset with the appropriate size.
    # Todo: Check if we need to keep the block size as 64
    data = TokenDataset(file_name, vocab_file=vocab_file, merges_file=merges_file, block_size=64)

    # Train the model! It will save pytorch_model.bin periodically and after completion.

    ai.train(data, batch_size=16, num_steps=2000)

    # Generate text from it!
    ai.generate(10, prompt="The camera that I bought")
`

I have verified that I am not going out of memory (the memory utilized is about 4.5/ 11 GB).

Can you please help me out?

**Comment by pdsing** [comment]
@minimaxir Any pointers here?

**Comment by minimaxir** [comment]
The 1000 steps means it is failing at saving the model (could be a number of issues related to the GPU). It might be best to set `save_every=0` for `train()` and see if that helps.

**Comment by pdsing** [comment]
@minimaxir Thanks for the input. The issue still persists. 


1. I think even with `save_every=0` in `train()`, it still tries to save the checkpoints after 1000 iterations. That is when the code crashes. I am attaching my code snippet and the error log for your reference. 
2. I checked and the memory consumption is still about 4.5 GB (on an 11 GB machine). 
3. It is able to save the weights if the number of iterations is less than 1000 (I checked with 900). So it is not a permissions issue.
 

Any help appreciated.

Relevant code snippet
`    file_name = "input2.txt"

    # Train a custom BPE Tokenizer on the downloaded text
    # This will save two files: aitextgen-vocab.json and aitextgen-merges.txt,
    # which are needed to rebuild the tokenizer.
    train_tokenizer(file_name)
    vocab_file = "aitextgen-vocab.json"
    merges_file = "aitextgen-merges.txt"

    # Instantiate aitextgen using the created tokenizer and config
    # ai = aitextgen(vocab_file=vocab_file, merges_file=merges_file, config=config)
    # Todo: Check if we need the config.json for this one
    ai = aitextgen(vocab_file=vocab_file, merges_file=merges_file, model="distilgpt2")

    # You can build datasets for training by creating TokenDatasets,
    # which automatically processes the dataset with the appropriate size.
    # Todo: Check if we need to keep the block size as 64
    data = TokenDataset(file_name, vocab_file=vocab_file, merges_file=merges_file, block_size=64)

    # Train the model! It will save pytorch_model.bin periodically and after completion.

    ai.train(data, batch_size=16, num_steps=2000, save_every=0)

    # Generate text from it!
    ai.generate(10, prompt="The camera that I bought")`



(gpt) pdsingh@pdsingh-MS-7C31:~/projects/pd/aitextgen$ python finetune_distilgpt.py 
[00:00:00] Reading files                            ████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                 100
[00:00:00] Tokenize words                           ████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 10378    /    10378
[00:00:00] Count pairs                              ████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 10378    /    10378
[00:00:00] Compute merges                           ████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 4743     /     4743

INFO:aitextgen.tokenizers:Saving aitextgen-vocab.json and aitextgen-merges.txt to the current directory. You will need both files to build the GPT2Tokenizer.
INFO:aitextgen:Loading distilgpt2 model from /aitextgen.
INFO:aitextgen:Using a custom tokenizer.
  0%|                                                                                                                                                             | 0/22940 [00:00<?, ?it/s]INFO:aitextgen.TokenDataset:Encoding 22,940 sets of tokens from input2.txt.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22940/22940 [00:00<00:00, 119253.10it/s]
WARNING:aitextgen:pytorch_model.bin already exists in /trained_model and will be overwritten!
GPU available: True, used: True
INFO:lightning:GPU available: True, used: True
No environment variable for node rank defined. Set as 0.
WARNING:lightning:No environment variable for node rank defined. Set as 0.
CUDA_VISIBLE_DEVICES: [0]
INFO:lightning:CUDA_VISIBLE_DEVICES: [0]
1,000 steps reached: saving model to /trained_model                                                                                                                                         
1,000 steps reached: generating sample texts.                                                                                                                                               
Loss: 3.860 — Avg: 3.898 — GPU Mem: 4517 MB:  50%|███████████████████████████████████████████████████                                                   | 1000/2000 [02:04<02:04,  8.04it/s]Traceback (most recent call last):
  File "finetune_distilgpt.py", line 30, in <module>
    ai.train(data, batch_size=16, num_steps=2000)
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/aitextgen/aitextgen.py", line 565, in train
    trainer.fit(train_model)
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 859, in fit
    self.single_gpu_train(model)
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 503, in single_gpu_train
    self.run_pretrain_routine(model)
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1015, in run_pretrain_routine
    self.train()
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 347, in train
    self.run_training_epoch()
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 419, in run_training_epoch
    _outputs = self.run_training_batch(batch, batch_idx)
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 638, in run_training_batch
    self.on_batch_end()
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/pytorch_lightning/trainer/callback_hook.py", line 63, in on_batch_end
    callback.on_batch_end(self, self.get_model())
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/aitextgen/train.py", line 187, in on_batch_end
    self.generate_sample_text(trainer, pl_module)
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/aitextgen/train.py", line 204, in generate_sample_text
    for output in outputs
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/aitextgen/train.py", line 204, in <listcomp>
    for output in outputs
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 2181, in decode
    sub_texts.append(self.convert_tokens_to_string(current_sub_text))
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/transformers/tokenization_gpt2.py", line 235, in convert_tokens_to_string
    text = "".join(tokens)
TypeError: sequence item 0: expected str instance, NoneType found
Exception ignored in: <function tqdm.__del__ at 0x7fbd7c538b90>
Traceback (most recent call last):
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/tqdm/std.py", line 1131, in __del__
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/tqdm/std.py", line 1344, in close
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/tqdm/std.py", line 1523, in display
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/tqdm/std.py", line 1134, in __repr__
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/tqdm/std.py", line 1484, in format_dict
TypeError: cannot unpack non-iterable NoneType object
(gpt) pdsingh@pdsingh-MS-7C31:~/projects/pd/aitextgen$ python finetune_distilgpt.py 
[00:00:00] Reading files                            ████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                 100
[00:00:00] Tokenize words                           ████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 10378    /    10378
[00:00:00] Count pairs                              ████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 10378    /    10378
[00:00:00] Compute merges                           ████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 4743     /     4743

INFO:aitextgen.tokenizers:Saving aitextgen-vocab.json and aitextgen-merges.txt to the current directory. You will need both files to build the GPT2Tokenizer.
INFO:aitextgen:Loading distilgpt2 model from /aitextgen.
INFO:aitextgen:Using a custom tokenizer.
  0%|                                                                                                                                                             | 0/22940 [00:00<?, ?it/s]INFO:aitextgen.TokenDataset:Encoding 22,940 sets of tokens from input2.txt.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22940/22940 [00:00<00:00, 121359.66it/s]
WARNING:aitextgen:pytorch_model.bin already exists in /trained_model and will be overwritten!
GPU available: True, used: True
INFO:lightning:GPU available: True, used: True
No environment variable for node rank defined. Set as 0.
WARNING:lightning:No environment variable for node rank defined. Set as 0.
CUDA_VISIBLE_DEVICES: [0]
INFO:lightning:CUDA_VISIBLE_DEVICES: [0]
1,000 steps reached: generating sample texts.                                                                                                                                               
Loss: 3.835 — Avg: 3.912 — GPU Mem: 4522 MB:  50%|███████████████████████████████████████████████████                                                   | 1000/2000 [01:57<01:57,  8.51it/s]Traceback (most recent call last):
  File "finetune_distilgpt.py", line 30, in <module>
    ai.train(data, batch_size=16, num_steps=2000, save_every=0)
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/aitextgen/aitextgen.py", line 565, in train
    trainer.fit(train_model)
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 859, in fit
    self.single_gpu_train(model)
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 503, in single_gpu_train
    self.run_pretrain_routine(model)
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1015, in run_pretrain_routine
    self.train()
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 347, in train
    self.run_training_epoch()
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 419, in run_training_epoch
    _outputs = self.run_training_batch(batch, batch_idx)
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 638, in run_training_batch
    self.on_batch_end()
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/pytorch_lightning/trainer/callback_hook.py", line 63, in on_batch_end
    callback.on_batch_end(self, self.get_model())
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/aitextgen/train.py", line 187, in on_batch_end
    self.generate_sample_text(trainer, pl_module)
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/aitextgen/train.py", line 204, in generate_sample_text
    for output in outputs
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/aitextgen/train.py", line 204, in <listcomp>
    for output in outputs
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 2181, in decode
    sub_texts.append(self.convert_tokens_to_string(current_sub_text))
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/transformers/tokenization_gpt2.py", line 235, in convert_tokens_to_string
    text = "".join(tokens)
TypeError: sequence item 0: expected str instance, NoneType found
Exception ignored in: <function tqdm.__del__ at 0x7fa6e3b6bb90>
Traceback (most recent call last):
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/tqdm/std.py", line 1131, in __del__
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/tqdm/std.py", line 1344, in close
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/tqdm/std.py", line 1523, in display
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/tqdm/std.py", line 1134, in __repr__
  File "/home/pdsingh/anaconda3/envs/gpt/lib/python3.7/site-packages/tqdm/std.py", line 1484, in format_dict
TypeError: cannot unpack non-iterable NoneType object

**Comment by pdsing** [comment]
@minimaxir Any other pointers?

**Comment by binkiebinkie** [comment]
I am getting a similar issue periodically when generating from this: ai.generate(n=1, prompt="sup morty", temperature=4.6, return_as_list=True). Also, are we able to leave the prompt empty? If I do, it doesn't seem to work. 
Here is the error: 
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\bink\.pyenv\pyenv-win\versions\3.6.4-amd64\lib\site-packages\aitextgen\aitextgen.py", line 291, in generate
    gen_texts = [self.tokenizer.decode(outputs[0], skip_special_tokens=True)]
  File "C:\Users\bink\.pyenv\pyenv-win\versions\3.6.4-amd64\lib\site-packages\transformers\tokenization_utils.py", line 2181, in decode
    sub_texts.append(self.convert_tokens_to_string(current_sub_text))
  File "C:\Users\bink\.pyenv\pyenv-win\versions\3.6.4-amd64\lib\site-packages\transformers\tokenization_gpt2.py", line 235, in convert_tokens_to_string
    text = "".join(tokens)
TypeError: sequence item 231: expected str instance, NoneType `
