### ISSUE TITLE
When training on local machine I get the error: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by farazk86** [minimaxir/aitextgen#77]
Hi,

I'm following your colab example to fine tune a model: https://colab.research.google.com/drive/15qBZx5y9rdaQSyWpsreMDnTiZ5IlN0zD?usp=sharing

It works fine on colab, but I'm training this on my local machine and I get the following error on ``ai.train``

```python
01/10/2021 21:32:21 — INFO — aitextgen — Downloading the 124M GPT-2 TensorFlow weights/config from Google's servers
01/10/2021 21:32:21 — INFO — aitextgen — Converting the 124M GPT-2 TensorFlow weights to PyTorch.
Traceback (most recent call last):
  File "C:/Users/FK~1/PycharmProjects/aitextgen/fine_tune_model.py", line 10, in <module>
    ai = aitextgen(tf_gpt2="124M", to_gpu=True)
  File "C:\Users\FK~1\PycharmProjects\aitextgen\venv\lib\site-packages\aitextgen\aitextgen.py", line 133, in __init__
    cache_dir,
  File "C:\Users\FK~1\PycharmProjects\aitextgen\venv\lib\site-packages\transformers\models\gpt2\convert_gpt2_original_tf_checkpoint_to_pytorch.py", line 34, in convert_gpt2_checkpoint_to_pytorch
    config = GPT2Config.from_json_file(gpt2_config_file)
  File "C:\Users\FK~1\PycharmProjects\aitextgen\venv\lib\site-packages\transformers\configuration_utils.py", line 486, in from_json_file
    config_dict = cls._dict_from_json_file(json_file)
  File "C:\Users\FK~1\PycharmProjects\aitextgen\venv\lib\site-packages\transformers\configuration_utils.py", line 493, in _dict_from_json_file
    return json.loads(text)
  File "C:\Users\FK~1\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\FK~1\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\FK~1\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by dudesparsh** [comment]
I am getting same issue on google colab

**Comment by minimaxir** [comment]
This was likely fixed in `0.4.0`: Can you try again?
